name: QRcraft
version: 1.0.4
api: 1.0.0
main: clodyx\qrcraft\QRcraftPlugIn
author: Clodyx
description: QRcraft by Clodyx
commands:
 qr:
  description: "Help page QRcraft"
  permission: clodyx.plugin.qrcraft
 qrt:
  description: "Test QR panel size"
  permission: clodyx.plugin.qrcraft
 qrc:
  description: "Create QR code panel"
  permission: clodyx.plugin.qrcraft
 qrl:
  description: "List QR panels IDs"
  permission: clodyx.plugin.qrcraft
 qrd:
  description: "Delete QR panel by ID"
  permission: clodyx.plugin.qrcraft
 qrp:
  description: "Teleport nearby QR panel by ID"
  permission: clodyx.plugin.qrcraft
permissions:
 clodyx.plugin.qrcraft:
  description: "clodyx.plugin.qrcraft"
  default: op